# Generated by Django 3.0 on 2019-12-31 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='is_kingdom_card',
            field=models.BooleanField(default=1),
        ),
    ]
