# Generated by Django 3.1.2 on 2020-10-06 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_readonly_uuid_and_require_iskingdom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='set_num',
        ),
    ]
